import java.awt.Component;
import java.awt.*;



public class ArrowChoices extends java.awt.Panel
{
	//insert class definition here

	public ArrowChoices()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(323,138);
		arrowPanel2 = new ArrowPanel();
		arrowPanel2.setBounds(16,5,32,32);
		add(arrowPanel2);
		arrowPanel3 = new ArrowPanel();
		arrowPanel3.setBounds(53,5,32,32);
		add(arrowPanel3);
		arrowPanel4 = new ArrowPanel();
		arrowPanel4.setBounds(90,5,32,32);
		add(arrowPanel4);
		arrowPanel5 = new ArrowPanel();
		arrowPanel5.setBounds(127,5,32,32);
		add(arrowPanel5);
		arrowPanel6 = new ArrowPanel();
		arrowPanel6.setBounds(164,5,32,32);
		add(arrowPanel6);
		arrowPanel7 = new ArrowPanel();
		arrowPanel7.setBounds(201,5,32,32);
		add(arrowPanel7);
		arrowPanel8 = new ArrowPanel();
		arrowPanel8.setBounds(238,5,32,32);
		add(arrowPanel8);
		arrowPanel9 = new ArrowPanel();
		arrowPanel9.setBounds(275,5,32,32);
		add(arrowPanel9);
		kintermEntry1 = new KintermEntry();
		kintermEntry1.setBounds(99,58,52,46);
		add(kintermEntry1);
		//}}
		arrowPanel2.setOrientation(ArrowPanel.UP);
		arrowPanel3.setOrientation(ArrowPanel.DOWN);
		arrowPanel4.setOrientation(ArrowPanel.RIGHT);
		arrowPanel5.setOrientation(ArrowPanel.LEFT);

		arrowPanel6.setOrientation(ArrowPanel.UP);
		arrowPanel7.setOrientation(ArrowPanel.DOWN);
		arrowPanel8.setOrientation(ArrowPanel.RIGHT);
		arrowPanel9.setOrientation(ArrowPanel.LEFT);

		arrowPanel6.setArrowColour(Color.red);
		arrowPanel7.setArrowColour(Color.red);
		arrowPanel8.setArrowColour(Color.red);
		arrowPanel9.setArrowColour(Color.red);
	}

	
	//{{DECLARE_CONTROLS
	ArrowPanel arrowPanel2;
	ArrowPanel arrowPanel3;
	ArrowPanel arrowPanel4;
	ArrowPanel arrowPanel5;
	ArrowPanel arrowPanel6;
	ArrowPanel arrowPanel7;
	ArrowPanel arrowPanel8;
	ArrowPanel arrowPanel9;
	KintermEntry kintermEntry1;
	//}}

	/**
	* We override this method so that nothing gets added to this component
	* @param comp the component to be added
	* @param constraints an object expressing layout contraints for this
	* component
	* @param index the position in the container's list at which to
	* insert the component.  -1 means insert at the end.
	* @see #remove
	* @see LayoutManager
	*/
	protected void addImpl(Component comp, Object constraints, int index) {
		//do nothing
	}

	public void setCurrentArrow(int currentArrow) {
		this.currentArrow = currentArrow;

			
	}

	public int getCurrentArrow() {
		return currentArrow;
	}

	public void setArrowFeature(int[] arrowFeature) {
		this.arrowFeature = arrowFeature;

			
	}

	public int[] getArrowFeature() {
		return arrowFeature;
	}

	public void setArrowFeature(int a, int b) {
		this.arrowFeature[a] = b;
	}

	public int getArrowFeature(int a) {
		return this.arrowFeature[a];
	}
	protected int currentArrow;
	protected int[] arrowFeature;
}
